/*
 * ============================================================
 * FILE: examples.mjs
 * PURPOSE: Provides validated troubleshooting-tree examples used to demonstrate Electrical Troubleshooter's diagnostic workflow.
 * ============================================================
 */

import { REQUIRED_SAFETY } from "./model.mjs";
const base=(id,title,nodes)=>({schemaVersion:1,id,title,safety:REQUIRED_SAFETY,startId:"isolation",nodes:[{id:"isolation",kind:"question",prompt:"Before any inspection, has the equipment been isolated, locked out where applicable, and verified de-energized by qualified personnel?",explanation:"This guide only continues with safe, non-energized, observational steps.",warning:REQUIRED_SAFETY,choices:[{label:"Yes — isolation and verification are complete",next:"visual"},{label:"No or uncertain",next:"stop"}]},{id:"stop",kind:"terminal",prompt:"Stop and obtain qualified assistance before continuing.",explanation:"Do not bypass isolation, lockout, guards, or protective devices. Follow site procedures and use qualified personnel.",warning:REQUIRED_SAFETY},...nodes]});
export const EXAMPLES={
 motor:base("motor-no-start","Motor does not start",[{id:"visual",kind:"question",prompt:"With the system safely isolated, is there visible damage, odor, leakage, or a tripped protective device documented by the site process?",explanation:"Observe only. Do not reset or bypass protection as part of this guide.",choices:[{label:"Yes — document it and stop for qualified service",next:"service"},{label:"No visible indication",next:"records"}]},{id:"records",kind:"terminal",prompt:"Review approved maintenance records, diagrams, and control-state indications with qualified personnel.",explanation:"Use the manufacturer documentation and site procedure to determine the next safe service step.",warning:"Do not energize exposed equipment for this educational guide."},{id:"service",kind:"terminal",prompt:"Keep the equipment isolated and obtain qualified service.",explanation:"Record observations and follow the facility escalation process.",warning:"Do not work on exposed energized equipment."}]),
 panel:base("control-panel-fault","Basic control-panel fault",[{id:"visual",kind:"question",prompt:"With isolation verified, are external labels, enclosure condition, and documented indicator states available to review without opening unsafe compartments?",explanation:"Read labels and records only; avoid contact with conductors or terminals.",choices:[{label:"Yes — information is available",next:"records"},{label:"No or enclosure condition is uncertain",next:"service"}]},{id:"records",kind:"terminal",prompt:"Compare the documented indicator state with the approved panel diagram and maintenance record.",explanation:"A qualified person should decide whether further testing is appropriate.",warning:"Do not defeat interlocks, bypass protective devices, or handle energized conductors."},{id:"service",kind:"terminal",prompt:"Stop and obtain qualified panel service.",explanation:"Maintain isolation and record the observed condition.",warning:"Do not work on exposed energized equipment."}]),
 sensor:base("sensor-not-responding","Sensor not responding",[{id:"visual",kind:"question",prompt:"With the equipment safely isolated, is the sensor housing, cable routing, and connector exterior visibly intact?",explanation:"This is an external visual check only. Do not probe live terminals.",choices:[{label:"Yes — exterior appears intact",next:"records"},{label:"No — damage or contamination is visible",next:"service"}]},{id:"records",kind:"terminal",prompt:"Review the approved sensor datasheet, connector keying, and service records with qualified personnel.",explanation:"Use manufacturer procedures for any measurement or replacement decision.",warning:"Do not work on exposed energized equipment."},{id:"service",kind:"terminal",prompt:"Keep the circuit isolated and obtain qualified service.",explanation:"Document the external condition and follow site escalation.",warning:"Do not work on exposed energized equipment."}]),
 power:base("power-supply-diagnostic","Power supply diagnostic",[{id:"visual",kind:"question",prompt:"With isolation verified, are enclosure vents, external cable condition, labels, and maintenance records free of obvious issues?",explanation:"Observe from outside the enclosure. Internal capacitors and stored energy require qualified handling.",choices:[{label:"Yes — no external issue observed",next:"records"},{label:"No or stored-energy risk is uncertain",next:"service"}]},{id:"records",kind:"terminal",prompt:"Review the approved power-supply documentation and maintenance procedure with qualified personnel.",explanation:"Qualified personnel determine discharge, testing, and replacement steps.",warning:"Do not work on exposed energized equipment or assume capacitors are discharged."},{id:"service",kind:"terminal",prompt:"Keep the supply isolated and obtain qualified service.",explanation:"Document observations without opening hazardous compartments.",warning:"Do not work on exposed energized equipment."}])
};
