import { randomUUID } from "node:crypto";
export const SCHEMA_VERSION=1;
export const REQUIRED_SAFETY="Do not work on exposed energized equipment. Isolate, lock out, and verify the equipment is de-energized; use qualified personnel where required.";
const text=value=>String(value??"").trim();
export function createTree({title="Untitled guide",nodes=[],startId=null,safety=REQUIRED_SAFETY}={}){return{schemaVersion:SCHEMA_VERSION,id:randomUUID(),title:text(title)||"Untitled guide",safety:text(safety),startId,nodes};}
export function nodeById(tree,id){return tree.nodes.find(node=>node.id===id);}
function validateNode(node,ids){if(!text(node.id))throw new Error("Each node needs an id.");if(!["question","terminal"].includes(node.kind))throw new Error(`Node ${node.id} has an invalid kind.`);if(!text(node.prompt))throw new Error(`Node ${node.id} needs a prompt.`);if(node.kind==="question"){if(!Array.isArray(node.choices)||node.choices.length<2)throw new Error(`Question ${node.id} needs at least two choices.`);for(const choice of node.choices){if(!text(choice.label)||!text(choice.next))throw new Error(`Question ${node.id} has an incomplete choice.`);if(!ids.has(choice.next))throw new Error(`Question ${node.id} points to missing node ${choice.next}.`);}}}
function containsUnsafeInstruction(tree){const corpus=[tree.title,tree.safety,...tree.nodes.flatMap(node=>[node.prompt,node.explanation,node.warning,...(node.choices??[]).map(choice=>choice.label)])].join(" ").toLowerCase();return corpus.split(/[.!?]/).some(sentence=>{const mentionsRisk=/(exposed|live|energized)/.test(sentence),mentionsAction=/(touch|work on|probe|measure)/.test(sentence),prohibits=/(do not|never|avoid|without)/.test(sentence);return mentionsRisk&&mentionsAction&&!prohibits;});}
export function findCycle(tree){const byId=new Map(tree.nodes.map(node=>[node.id,node]));const visiting=new Set(),visited=new Set();function walk(id){if(visiting.has(id))return true;if(visited.has(id))return false;visiting.add(id);for(const next of byId.get(id).choices?.map(choice=>choice.next)??[])if(walk(next))return true;visiting.delete(id);visited.add(id);return false}return walk(tree.startId);}
export function validateTree(value){if(Number(value.schemaVersion)!==SCHEMA_VERSION)throw new Error(`Unsupported schema version; expected ${SCHEMA_VERSION}.`);const tree=createTree(value);if(!tree.safety.toLowerCase().includes("do not work on exposed energized")||!tree.safety.toLowerCase().includes("isolate")||!tree.safety.toLowerCase().includes("qualified"))throw new Error("Safety statement must prohibit exposed energized work and require isolation and qualified personnel boundaries.");if(!Array.isArray(tree.nodes)||tree.nodes.length===0)throw new Error("A tree needs at least one node.");const ids=new Set(tree.nodes.map(node=>node.id));if(ids.size!==tree.nodes.length)throw new Error("Node ids must be unique.");if(!ids.has(tree.startId))throw new Error("startId must reference a node.");tree.nodes.forEach(node=>validateNode(node,ids));if(findCycle(tree))throw new Error("Decision trees cannot contain cycles.");if(containsUnsafeInstruction(tree))throw new Error("Safety validation rejected a potentially unsafe exposed/live/energized work instruction.");return tree;}
export function start(tree){const safe=validateTree(tree);return{tree:safe,currentId:safe.startId,history:[]};}
export function current(state){return nodeById(state.tree,state.currentId);}
export function choose(state,choiceIndex){const node=current(state);if(node.kind!=="question")throw new Error("Terminal nodes have no choices.");const choice=node.choices[choiceIndex];if(!choice)throw new Error("Choice does not exist.");return{...state,currentId:choice.next,history:[...state.history,node.id]};}
export function back(state){const history=[...state.history],id=history.pop();return id?{...state,currentId:id,history}:state;}
export function reset(state){return{...state,currentId:state.tree.startId,history:[]};}
export function treeToYaml(tree){return`# This document is JSON syntax, which is valid YAML 1.2.\n${JSON.stringify(validateTree(tree),null,2)}\n`;}
export function parseProject(textContent){const cleaned=String(textContent).replace(/^\s*#.*\n/,"");try{return validateTree(JSON.parse(cleaned));}catch(error){throw new Error(`Import requires a version ${SCHEMA_VERSION} JSON document or JSON-form YAML 1.2 document: ${error.message}`);}}
